"""Added initial tables

Revision ID: 12e9bafcb8b2
Revises: 66638893491a
Create Date: 2023-06-23 00:16:14.262509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e9bafcb8b2'
down_revision = '66638893491a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('food_items_sub_category_id_fkey', 'food_items', type_='foreignkey')
    op.drop_column('food_items', 'sub_category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_items', sa.Column('sub_category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('food_items_sub_category_id_fkey', 'food_items', 'sub_categories', ['sub_category_id'], ['id'])
    # ### end Alembic commands ###
